export const main = {
  GET_UTILITY_LISTING: "MAIN_GET_UTILITY_LISTING",
  GET_UTILITY_LISTING_FAIL: "MAIN_GET_UTILITY_LISTING_FAIL",
  GET_GLOBAL_INFO_SUCCESS: "MAIN_GET_GLOBAL_INFO_SUCCESS",
  GET_GLOBAL_INFO_FAIL: "MAIN_GET_GLOBAL_INFO_FAIL",
  SET_LOADING: "MAIN_SET_LOADING",
  CHANGE_CLIENT_VIEW: "MAIN_CHANGE_CLIENT_VIEW"
};

export const auth = {
  SET_LOADING: "AUTH_SET_LOADING",
  SET_SUCCESS: "AUTH_SET_SUCCESS",
  SET_ERRORS: "AUTH_SET_ERRORS",
  RESET_PASSWORD: "AUTH_RESET_PASSWORD",
  RESET_PASSWORD_FAIL: "AUTH_RESET_PASSWORD_FAIL",
  SET_NEW_PASSWORD: "AUTH_SET_NEW_PASSWORD",
  SET_NEW_PASSWORD_FAIL: "AUTH_SET_NEW_PASSWORD_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL"
};

export const signUp = {
  SET_LOADING: "SIGNUP_SET_LOADING",
  SET_SUCCESS: "SIGNUP_SET_SUCCESS",
  SET_ERRORS: "SIGNUP_SET_ERRORS",
  SIGNUP: "SIGNUP",
  SIGNUP_FAIL: "SIGNUP_FAIL"
};

export const home = {
  SET_LOADING: "HOME_SET_LOADING",
  SET_DASHBOARD_DATA_CLEAR: "HOME_DASHBOARD_DATA_CLEAR",
  GET_DASHBOARD_DATA: "HOME_GET_DASHBOARD_DATA",
  GET_DASHBOARD_DATA_SUCCESS: "HOME_GET_DASHBOARD_DATA_SUCCESS",
  GET_DASHBOARD_DATA_FAIL: "HOME_GET_DASHBOARD_DATA_FAIL",
  MARK_READ: "HOME_MARK_READ",
  MARK_UNREAD: "HOME_MARK_UNREAD"
};

export const inbox = {
  SET_LOADING: "INBOX_SET_LOADING",
  GET_MESSAGES: "INBOX_GET_MESSAGES",
  GET_MESSAGES_FAIL: "INBOX_GET_MESSAGES_FAIL",
  GET_MESSAGES_FOR_FILTER: "INBOX_GET_MESSAGES_FOR_FILTER",
  GET_MESSAGES_FOR_FILTER_FAIL: "GET_MESSAGES_FOR_FILTER_FAIL",
  CLEAR: "INBOX_CLEAR",
  ARCHIVE: "INBOX_ARCHIVE",
  MARK_AS_READ: "INBOX_MARK_AS_READ",
  MARK_AS_UNREAD: "INBOX_MARK_AS_UNREAD"
};

export const payment = {
  SET_LOADING: "PAYMENT_SET_LOADING",
  GET_PAYMENT_METHODS: "PAYMENT_GET_PAYMENT_METHODS",
  SET_SELECTED_CARD: "PAYMENT_SET_SELECTED_CARD",
  GET_PAYMENT_METHODS_FAIL: "PAYMENT_GET_PAYMENT_METHODS_FAIL",
  GET_PAYMENT_HISTORY: "PAYMENT_GET_PAYMENT_HISTORY",
  GET_PAYMENT_HISTORY_FAIL: "PAYMENT_GET_PAYMENT_HISTORY_FAIL",
  ADD_CARD: "PAYMENT_ADD_CARD",
  ADD_CARD_SUCCESS: "PAYMENT_ADD_CARD_SUCCESS",
  ADD_CARD_LOCALLY: "PAYMENT_ADD_CARD_LOCALLY",
  ADD_CARD_FAIL: "PAYMENT_ADD_CARD_FAIL",
  UPDATE_CARD_SUCCESS: "PAYMENT_UPDATE_CARD_SUCCESS",
  UPDATE_CARD_LOCALLY: "PAYMENT_UPDATE_CARD_LOCALLY",
  UPDATE_CARD_FAIL: "PAYMENT_UPDATE_CARD_FAIL",
  DELETE_CARD_SUCCESS: "PAYMENT_DELETE_CARD_SUCCESS",
  DELETE_CARD_LOCALLY: "PAYMENT_DELETE_CARD_LOCALLY",
  SET_DEFAULT_SOURCE: "PAYMENT_SET_DEFAULT_SOURCE",
  CHARGE_FOR_MEMBERSHIP: "PAYMENT_CHARGE_FOR_MEMBERSHIP",
  CHARGE_FOR_MEMBERSHIP_SUCCESS: "PAYMENT_CHARGE_FOR_MEMBERSHIP_SUCCESS",
  CHARGE_FOR_MEMBERSHIP_FAIL: "PAYMENT_CHARGE_FOR_MEMBERSHIP_FAIL",
  SET_STRIPE_TOKEN: "PAYMENT_SET_STRIPE_TOKEN:"
};

export const inboxChat = {
  SET_LOADING: "INBOX_CHAT_SET_CHAT_LOADING",
  SET_SENDING: "INBOX_CHAT_SET_SENDING",
  GET_DATA: "INBOX_CHAT_GET_DATA",
  GET_DATA_FAIL: "INBOX_CHAT_GET_DATA_FAIL",
  SEND_MESSAGE: "INBOX_CHAT_SEND_MESSAGE",
  SEND_MESSAGE_FAIL: "INBOX_CHAT_SEND_MESSAGE_FAIL",
  ADD_MSG: "INBOX_CHAT_ADD_MSG",
  CLEAR: "INBOX_CHAT_CLEAR"
};

export const account = {
  SET_LOADING: "ACCOUNT_SET_LOADING",
  GET_PROFILE: "ACCOUNT_GET_PROFILE",
  GET_PROFILE_FAIL: "ACCOUNT_GET_PROFILE_FAIL",
  UPDATE_CONTACTS: "ACCOUNT_UPDATE_CONTACTS",
  UPDATE_CONTACTS_SUCCESS: "ACCOUNT_UPDATE_CONTACTS_SUCCESS",
  UPDATE_CONTACTS_FAIL: "ACCOUNT_UPDATE_CONTACTS_FAIL",
  UPDATE_PASSWORD: "ACCOUNT_UPDATE_PASSWORD",
  UPDATE_PASSWORD_SUCCESS: "ACCOUNT_UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAIL: "ACCOUNT_UPDATE_PASSWORD_FAIL",
  GET_NOTIFICATION_SETTINGS: "ACCOUNT_GET_NOTIFICATION_SETTINGS",
  GET_NOTIFICATION_SETTINGS_FAIL: "ACCOUNT_GET_NOTIFICATION_SETTINGS_FAIL",
  UPDATE_NOTIFICATIONS_SUCCESS: "ACCOUNT_UPDATE_NOTIFICATIONS_SUCCESS",
  UPDATE_NOTIFICATIONS_FAIL: "ACCOUNT_UPDATE_NOTIFICATIONS_FAIL",
  UPDATE_NEWSLETTERS_SUCCESS: "ACCOUNT_UPDATE_NEWSLETTERS_SUCCESS",
  UPDATE_NEWSLETTERS_FAIL: "ACCOUNT_UPDATE_NEWSLETTERS_FAIL"
};

export const membershipListing = {
  SET_LOADING: "MEMBERSHIPS_SET_LOADING",
  SET_SUCCESS: "MEMBERSHIPS_SET_SUCCESS",
  GET_MEMBERSHIPS: "MEMBERSHIPS_GET_MEMBERSHIPS",
  SET_MEMBERSHIPS_CLEAR: "MEMBERSHIPS_SET_MEMBERSHIPS_CLEAR",
  GET_MEMBERSHIPS_FAIL: "MEMBERSHIPS_GET_MEMBERSHIPS_FAIL",
  GET_NEW_MEMBERSHIPS: "MEMBERSHIPS_GET_NEW_MEMBERSHIPS",
  GET_NEW_MEMBERSHIPS_FAIL: "MEMBERSHIPS_GET_NEW_MEMBERSHIPS_FAIL",
  ADD_NEW_MEMBERSHIP: "MEMBERSHIPS_ADD_NEW_MEMBERSHIP",
  ADD_NEW_MEMBERSHIP_SUCCESS: "MEMBERSHIPS_ADD_NEW_MEMBERSHIP_SUCCESS",
  ADD_NEW_MEMBERSHIP_FAIL: "MEMBERSHIPS_ADD_NEW_MEMBERSHIP_FAIL",
  GET_BILLING_PLANS: "MEMBERSHIPS_GET_BILLING_PLANS",
  GET_BILLING_PLANS_FAIL: "MEMBERSHIPS_GET_BILLING_PLANS_FAIL",
  GET_UPGRADE_OPTIONS: "MEMBERSHIPS_GET_UPGRADE_OPTIONS",
  GET_UPGRADE_OPTIONS_FAIL: "MEMBERSHIPS_GET_UPGRADE_OPTIONS_FAIL",
  DELETE: "MEMBERSHIPS_DELETE_MEMBERSHIP",
  DELETE_SUCCESS: "MEMBERSHIPS_DELETE_SUCCESS",
  DELETE_FAIL: "MEMBERSHIPS_DELETE_FAIL",
  UPGRADE: "MEMBERSHIPS_UPGRADE",
  UPGRADE_SUCCESS: "MEMBERSHIPS_UPGRADE_SUCCESS",
  UPGRADE_LOCALLY: "MEMBERSHIPS_UPGRADE_LOCALLY",
  UPGRADE_FAIL: "MEMBERSHIPS_UPGRADE_FAIL",
  UPGRADE_CLEAN: "MEMBERSHIPS_UPGRADE_CLEAN",
  DOWNGRADE: "MEMBERSHIPS_DOWNGRADE",
  DOWNGRADE_SUCCESS: "MEMBERSHIPS_DOWNGRADE_SUCCESS",
  DOWNGRADE_LOCALLY: "MEMBERSHIPS_DOWNGRADE_LOCALLY",
  DOWNGRADE_FAIL: "MEMBERSHIPS_DOWNGRADE_FAIL"
};

export const membership = {
  SET_LOADING: "MEMBERSHIP_SET_LOADING",
  GET_MEMBER_DATA: "MEMBERSHIP_GET_MEMBER_DATA",
  GET_MEMBER_DATA_SUCCESS: "MEMBERSHIP_GET_MEMBER_DATA_SUCCESS",
  CHANGE_MEMBER_DATA_YELP_AVVO_SUCCESS: "MEMBERSHIP_CHANGE_MEMBER_DATA_YELP_AVVO_SUCCESS",
  GET_MEMBER_DATA_FAIL: "MEMBERSHIP_GET_MEMBER_DATA_FAIL",
  GET_SOCIAL_GROUPS: "MEMBERSHIP_GET_SOCIAL_GROUPS",
  GET_SOCIAL_GROUPS_FAIL: "MEMBERSHIP_GET_SOCIAL_GROUPS_FAIL",
  SUBMIT_CHANGES_SUCCESS: "MEMBERSHIP_SUBMIT_CHANGES_SUCCESS",
  SUBMIT_CHANGES_FAIL: "MEMBERSHIP_SUBMIT_CHANGES_FAIL",
  GET_PRODUCT_NAME: "MEMBERSHIP_GET_PRODUCT_NAME",
  GET_PRODUCT_NAME_SUCCESS: "MEMBERSHIP_GET_PRODUCT_NAME_SUCCESS",
  GET_PRODUCT_NAME_FAIL: "MEMBERSHIP_GET_PRODUCT_NAME_FAIL",
  SET_MEMBERSHIP_DATA_CLEAR: "MEMBERSHIP_SET_MEMBERSHIP_DATA_CLEAR"
};

export const payPerLead = {
  SET_LOADING: "PPL_SET_LOADING",
  GET_LEADS: "PPL_GET_LEADS",
  GET_LEADS_FAIL: "PPL_GET_LEADS_FAIL",
  SET_LEADS_CLEAR: "PPL_SET_LEADS_CLEAR",
  GET_LEADS_BY_FILTER: "PPL_GET_LEADS_BY_FILTER",
  SET_LEAD_NO_INTEREST: "PPL_SET_LEAD_NO_INTEREST",
  GET_LEADS_BY_FILTER_FALSE: "PPL_GET_LEADS_BY_FILTER_FALSE"
};

export const payPerLeadDetail = {
  SET_LOADING: "PPL_DETAIL_SET_LOADING",
  RESET_SUCCESS: "PPL_DETAIL_RESET_SUCCESS",
  RESET_ERROR: "PPL_DETAIL_RESET_ERROR",
  GET_LEAD: "PPL_DETAIL_GET_LEAD",
  GET_LEAD_FAIL: "PPL_DETAIL_GET_LEAD_FAIL",
  BUY_LEAD: "PPL_DETAIL_BUY_LEAD",
  BUY_LEAD_FAIL: "PPL_DETAIL_BUY_LEAD_FAIL",
  HIDE_LEAD: "PPL_DETAIL_HIDE_LEAD",
  HIDE_LEAD_FAIL: "PPL_DETAIL_HIDE_LEAD_FAIL",
  CLEAR_LEAD: "PPL_DETAIL_CLEAR_LEAD"
};

export const callHistory = {
  GET_CALL_DATA_SUCCESS: "CALL_HISTORY_GET_CALL_DATA_SUCCESS",
  GET_CALL_DATA_FAIL: "CALL_HISTORY_GET_CALL_DATA_FAIL",
  SET_CALL_DATA_CLEAN: "CALL_HISTORY_SET_CALL_DATA_CLEAN",
  SET_CALL_PRELOADER: "CALL_HISTORY_SET_CALL_PRELOADER"
};

export const registration = {
  GET_DATA_STEP_1: "REGISTRATION_GET_DATA_STEP_1",
  SAVE_STEP_DATA: "REGISTRATION_SAVE_STEP_DATA",
  SET_GLOBAL_LOADING: "REGISTRATION_SET_GLOBAL_LOADING",
  SAVE_LISTING_DATA: "REGISTRATION_SAVE_LISTING_DATA",
  SET_BILLING_PLANS: "REGISTRATION_SET_BILLING_PLANS",
  SET_LOADING: "REGISTRATION_SET_LOADING",
  SET_SUCCESS: "REGISTRATION_SET_SUCCESS",
  SET_LEAD_ID: "REGISTRATION_SET_LEAD_ID",
  SET_ERROR: "REGISTRATION_SET_ERROR",
  CLEAR_ERRORS: "REGISTRATION_CLEAR_ERRORS",
  SET_INVOICE_ID: "REGISTRATION_SET_INVOICE_ID",
  GET_PRACTICES: "REGISTRATION_GET_PRACTICES"
};

export const performance = {
  SET_LOADING: "PERFORMANCE_DETAIL_SET_LOADING",

  GET_LEADS_BY_MONTH: "PERFORMANCE_GET_LEADS_BY_MONTH",
  GET_LEADS_BY_YEAR: "PERFORMANCE_GET_LEADS_BY_YEAR",
  GET_LEADS_BY_WEEK: "PERFORMANCE_GET_LEADS_BY_WEEK",

  GET_LEADS_BY_WEEK_SUCCESS: "PERFORMANCE_GET_LEADS_BY_WEEK_SUCCESS",
  GET_LEADS_BY_YEAR_SUCCESS: "PERFORMANCE_GET_LEADS_BY_YEAR_SUCCESS",
  GET_LEADS_BY_MONTH_SUCCESS: "PERFORMANCE_GET_LEADS_BY_MONTH_SUCCESS",
  GET_ALL_LEADS_SUCCESS: "GET_ALL_LEADS_SUCCESS",
  GET_TRAFFIC_HISTORY_SUCCESS: "GET_TRAFFIC_HISTORY_SUCCESS",
  GET_TRAFFIC_SOURCE_SUCCESS: "GET_TRAFFIC_SOURCE_SUCCESS",
  GET_GEO_CHART_SUCCESS: "GET_GEO_CHART_SUCCESS",

  GET_LEADS_BY_WEEK_FAIL: "PERFORMANCE_GET_LEADS_BY_WEEK_FAIL",
  GET_LEADS_BY_YEAR_FAIL: "PERFORMANCE_GET_LEADS_BY_YEAR_FAIL",
  GET_LEADS_BY_MONTH_FAIL: "PERFORMANCE_GET_LEADS_BY_MONTH_FAIL",
  GET_ALL_LEADS_FAIL: "GET_ALL_LEADS_FAIL",
  GET_TRAFFIC_HISTORY_FAIL: "GET_TRAFFIC_HISTORY_FAIL",
  GET_TRAFFIC_SOURCE_FAIL: "GET_TRAFFIC_SOURCE_FAIL",
  GET_GEO_CHART_FAIL: "GET_GEO_CHART_FAIL"
};

export const notification = {
  SET_LOADING: "NOTIFICATION_SET_LOADING",
  MARK_READ: "NOTIFICATION_MARK_READ",
  MARK_UNREAD: "NOTIFICATION_MARK_UNREAD"
};
